// lib/continents.ts
// Continent (code ISO simplifié) par pays, indexé par le nom anglais world-atlas.
// Généré une fois via i18n-iso-countries + countries-list (pas de dépendance runtime).

export type ContinentCode = "AF" | "AN" | "AS" | "EU" | "NA" | "OC" | "SA";

export const COUNTRY_CONTINENT: Record<string, ContinentCode> = {
  "Fiji": "OC",
  "Tanzania": "AF",
  "W. Sahara": "AF",
  "Canada": "NA",
  "United States of America": "NA",
  "Kazakhstan": "AS",
  "Uzbekistan": "AS",
  "Papua New Guinea": "OC",
  "Indonesia": "AS",
  "Argentina": "SA",
  "Chile": "SA",
  "Dem. Rep. Congo": "AF",
  "Somalia": "AF",
  "Kenya": "AF",
  "Sudan": "AF",
  "Chad": "AF",
  "Haiti": "NA",
  "Dominican Rep.": "NA",
  "Russia": "AS",
  "Bahamas": "NA",
  "Falkland Is.": "SA",
  "Norway": "EU",
  "Greenland": "NA",
  "Fr. S. Antarctic Lands": "AN",
  "Timor-Leste": "OC",
  "South Africa": "AF",
  "Lesotho": "AF",
  "Mexico": "NA",
  "Uruguay": "SA",
  "Brazil": "SA",
  "Bolivia": "SA",
  "Peru": "SA",
  "Colombia": "SA",
  "Panama": "NA",
  "Costa Rica": "NA",
  "Nicaragua": "NA",
  "Honduras": "NA",
  "El Salvador": "NA",
  "Guatemala": "NA",
  "Belize": "NA",
  "Venezuela": "SA",
  "Guyana": "SA",
  "Suriname": "SA",
  "France": "EU",
  "Ecuador": "SA",
  "Puerto Rico": "NA",
  "Jamaica": "NA",
  "Cuba": "NA",
  "Zimbabwe": "AF",
  "Botswana": "AF",
  "Namibia": "AF",
  "Senegal": "AF",
  "Mali": "AF",
  "Mauritania": "AF",
  "Benin": "AF",
  "Niger": "AF",
  "Nigeria": "AF",
  "Cameroon": "AF",
  "Togo": "AF",
  "Ghana": "AF",
  "Côte d'Ivoire": "AF",
  "Guinea": "AF",
  "Guinea-Bissau": "AF",
  "Liberia": "AF",
  "Sierra Leone": "AF",
  "Burkina Faso": "AF",
  "Central African Rep.": "AF",
  "Congo": "AF",
  "Gabon": "AF",
  "Eq. Guinea": "AF",
  "Zambia": "AF",
  "Malawi": "AF",
  "Mozambique": "AF",
  "eSwatini": "AF",
  "Angola": "AF",
  "Burundi": "AF",
  "Israel": "AS",
  "Lebanon": "AS",
  "Madagascar": "AF",
  "Palestine": "AS",
  "Gambia": "AF",
  "Tunisia": "AF",
  "Algeria": "AF",
  "Jordan": "AS",
  "United Arab Emirates": "AS",
  "Qatar": "AS",
  "Kuwait": "AS",
  "Iraq": "AS",
  "Oman": "AS",
  "Vanuatu": "OC",
  "Cambodia": "AS",
  "Thailand": "AS",
  "Laos": "AS",
  "Myanmar": "AS",
  "Vietnam": "AS",
  "North Korea": "AS",
  "South Korea": "AS",
  "Mongolia": "AS",
  "India": "AS",
  "Bangladesh": "AS",
  "Bhutan": "AS",
  "Nepal": "AS",
  "Pakistan": "AS",
  "Afghanistan": "AS",
  "Tajikistan": "AS",
  "Kyrgyzstan": "AS",
  "Turkmenistan": "AS",
  "Iran": "AS",
  "Syria": "AS",
  "Armenia": "AS",
  "Sweden": "EU",
  "Belarus": "EU",
  "Ukraine": "EU",
  "Poland": "EU",
  "Austria": "EU",
  "Hungary": "EU",
  "Moldova": "EU",
  "Romania": "EU",
  "Lithuania": "EU",
  "Latvia": "EU",
  "Estonia": "EU",
  "Germany": "EU",
  "Bulgaria": "EU",
  "Greece": "EU",
  "Turkey": "AS",
  "Albania": "EU",
  "Croatia": "EU",
  "Switzerland": "EU",
  "Luxembourg": "EU",
  "Belgium": "EU",
  "Netherlands": "EU",
  "Portugal": "EU",
  "Spain": "EU",
  "Ireland": "EU",
  "New Caledonia": "OC",
  "Solomon Is.": "OC",
  "New Zealand": "OC",
  "Australia": "OC",
  "Sri Lanka": "AS",
  "China": "AS",
  "Taiwan": "AS",
  "Italy": "EU",
  "Denmark": "EU",
  "United Kingdom": "EU",
  "Iceland": "EU",
  "Azerbaijan": "AS",
  "Georgia": "AS",
  "Philippines": "AS",
  "Malaysia": "AS",
  "Brunei": "AS",
  "Slovenia": "EU",
  "Finland": "EU",
  "Slovakia": "EU",
  "Czechia": "EU",
  "Eritrea": "AF",
  "Japan": "AS",
  "Paraguay": "SA",
  "Yemen": "AS",
  "Saudi Arabia": "AS",
  "Antarctica": "AN",
  "N. Cyprus": "EU",
  "Cyprus": "EU",
  "Morocco": "AF",
  "Egypt": "AF",
  "Libya": "AF",
  "Ethiopia": "AF",
  "Djibouti": "AF",
  "Somaliland": "AF",
  "Uganda": "AF",
  "Rwanda": "AF",
  "Bosnia and Herz.": "EU",
  "Macedonia": "EU",
  "Serbia": "EU",
  "Montenegro": "EU",
  "Kosovo": "EU",
  "Trinidad and Tobago": "NA",
  "S. Sudan": "AF",
  "Vatican": "EU",
  "Micronesia": "OC",
  "Marshall Is.": "OC",
  "Tonga": "OC",
  "Singapore": "AS",
  "Seychelles": "AF",
  "São Tomé and Principe": "AF",
  "San Marino": "EU",
  "Samoa": "OC",
  "St. Vin. and Gren.": "NA",
  "Saint Lucia": "NA",
  "St. Kitts and Nevis": "NA",
  "Palau": "OC",
  "Nauru": "OC",
  "Monaco": "EU",
  "Mauritius": "AF",
  "Malta": "EU",
  "Maldives": "AS",
  "Liechtenstein": "EU",
  "Kiribati": "OC",
  "Grenada": "NA",
  "Dominica": "NA",
  "Comoros": "AF",
  "Cabo Verde": "AF",
  "Barbados": "NA",
  "Bahrain": "AS",
  "Antigua and Barb.": "NA",
  "Andorra": "EU",
};
