// lib/countryInfo.ts
// Noms français et drapeaux, indexés par le nom anglais utilisé par les données
// world-atlas (properties.name). Généré une fois via i18n-iso-countries + calcul
// des drapeaux à partir des codes ISO alpha-2 (pas de dépendance runtime).

export type CountryInfo = { fr: string; flag: string };

export const COUNTRY_INFO: Record<string, CountryInfo> = {
  "Fiji": { fr: "Fidji", flag: "🇫🇯" },
  "Tanzania": { fr: "Tanzanie", flag: "🇹🇿" },
  "W. Sahara": { fr: "Sahara occidental", flag: "🇪🇭" },
  "Canada": { fr: "Canada", flag: "🇨🇦" },
  "United States of America": { fr: "États-Unis", flag: "🇺🇸" },
  "Kazakhstan": { fr: "Kazakhstan", flag: "🇰🇿" },
  "Uzbekistan": { fr: "Ouzbékistan", flag: "🇺🇿" },
  "Papua New Guinea": { fr: "Papouasie-Nouvelle-Guinée", flag: "🇵🇬" },
  "Indonesia": { fr: "Indonésie", flag: "🇮🇩" },
  "Argentina": { fr: "Argentine", flag: "🇦🇷" },
  "Chile": { fr: "Chili", flag: "🇨🇱" },
  "Dem. Rep. Congo": { fr: "République démocratique du Congo", flag: "🇨🇩" },
  "Somalia": { fr: "Somalie", flag: "🇸🇴" },
  "Kenya": { fr: "Kenya", flag: "🇰🇪" },
  "Sudan": { fr: "Soudan", flag: "🇸🇩" },
  "Chad": { fr: "Tchad", flag: "🇹🇩" },
  "Haiti": { fr: "Haïti", flag: "🇭🇹" },
  "Dominican Rep.": { fr: "République Dominicaine", flag: "🇩🇴" },
  "Russia": { fr: "Russie", flag: "🇷🇺" },
  "Bahamas": { fr: "Bahamas", flag: "🇧🇸" },
  "Falkland Is.": { fr: "Îles Malouines", flag: "🇫🇰" },
  "Norway": { fr: "Norvège", flag: "🇳🇴" },
  "Greenland": { fr: "Groenland", flag: "🇬🇱" },
  "Fr. S. Antarctic Lands": { fr: "Terres australes françaises", flag: "🇹🇫" },
  "Timor-Leste": { fr: "Timor-Leste", flag: "🇹🇱" },
  "South Africa": { fr: "Afrique du Sud", flag: "🇿🇦" },
  "Lesotho": { fr: "Lesotho", flag: "🇱🇸" },
  "Mexico": { fr: "Mexique", flag: "🇲🇽" },
  "Uruguay": { fr: "Uruguay", flag: "🇺🇾" },
  "Brazil": { fr: "Brésil", flag: "🇧🇷" },
  "Bolivia": { fr: "Bolivie", flag: "🇧🇴" },
  "Peru": { fr: "Pérou", flag: "🇵🇪" },
  "Colombia": { fr: "Colombie", flag: "🇨🇴" },
  "Panama": { fr: "Panama", flag: "🇵🇦" },
  "Costa Rica": { fr: "Costa Rica", flag: "🇨🇷" },
  "Nicaragua": { fr: "Nicaragua", flag: "🇳🇮" },
  "Honduras": { fr: "Honduras", flag: "🇭🇳" },
  "El Salvador": { fr: "El Salvador", flag: "🇸🇻" },
  "Guatemala": { fr: "Guatemala", flag: "🇬🇹" },
  "Belize": { fr: "Belize", flag: "🇧🇿" },
  "Venezuela": { fr: "Venezuela", flag: "🇻🇪" },
  "Guyana": { fr: "Guyana", flag: "🇬🇾" },
  "Suriname": { fr: "Suriname", flag: "🇸🇷" },
  "France": { fr: "France", flag: "🇫🇷" },
  "Ecuador": { fr: "Équateur", flag: "🇪🇨" },
  "Puerto Rico": { fr: "Porto Rico", flag: "🇵🇷" },
  "Jamaica": { fr: "Jamaïque", flag: "🇯🇲" },
  "Cuba": { fr: "Cuba", flag: "🇨🇺" },
  "Zimbabwe": { fr: "Zimbabwe", flag: "🇿🇼" },
  "Botswana": { fr: "Botswana", flag: "🇧🇼" },
  "Namibia": { fr: "Namibie", flag: "🇳🇦" },
  "Senegal": { fr: "Sénégal", flag: "🇸🇳" },
  "Mali": { fr: "Mali", flag: "🇲🇱" },
  "Mauritania": { fr: "Mauritanie", flag: "🇲🇷" },
  "Benin": { fr: "Bénin", flag: "🇧🇯" },
  "Niger": { fr: "Niger", flag: "🇳🇪" },
  "Nigeria": { fr: "Nigéria", flag: "🇳🇬" },
  "Cameroon": { fr: "Cameroun", flag: "🇨🇲" },
  "Togo": { fr: "Togo", flag: "🇹🇬" },
  "Ghana": { fr: "Ghana", flag: "🇬🇭" },
  "Côte d'Ivoire": { fr: "Côte-d'Ivoire", flag: "🇨🇮" },
  "Guinea": { fr: "Guinée", flag: "🇬🇳" },
  "Guinea-Bissau": { fr: "Guinée-Bissau", flag: "🇬🇼" },
  "Liberia": { fr: "Libéria", flag: "🇱🇷" },
  "Sierra Leone": { fr: "Sierra Leone", flag: "🇸🇱" },
  "Burkina Faso": { fr: "Burkina Faso", flag: "🇧🇫" },
  "Central African Rep.": { fr: "République Centrafricaine", flag: "🇨🇫" },
  "Congo": { fr: "République du Congo", flag: "🇨🇬" },
  "Gabon": { fr: "Gabon", flag: "🇬🇦" },
  "Eq. Guinea": { fr: "Guinée équatoriale", flag: "🇬🇶" },
  "Zambia": { fr: "Zambie", flag: "🇿🇲" },
  "Malawi": { fr: "Malawi", flag: "🇲🇼" },
  "Mozambique": { fr: "Mozambique", flag: "🇲🇿" },
  "eSwatini": { fr: "Eswatini", flag: "🇸🇿" },
  "Angola": { fr: "Angola", flag: "🇦🇴" },
  "Burundi": { fr: "Burundi", flag: "🇧🇮" },
  "Israel": { fr: "Israël", flag: "🇮🇱" },
  "Lebanon": { fr: "Liban", flag: "🇱🇧" },
  "Madagascar": { fr: "Madagascar", flag: "🇲🇬" },
  "Palestine": { fr: "Palestine", flag: "🇵🇸" },
  "Gambia": { fr: "Gambie", flag: "🇬🇲" },
  "Tunisia": { fr: "Tunisie", flag: "🇹🇳" },
  "Algeria": { fr: "Algérie", flag: "🇩🇿" },
  "Jordan": { fr: "Jordanie", flag: "🇯🇴" },
  "United Arab Emirates": { fr: "Émirats Arabes Unis", flag: "🇦🇪" },
  "Qatar": { fr: "Qatar", flag: "🇶🇦" },
  "Kuwait": { fr: "Koweït", flag: "🇰🇼" },
  "Iraq": { fr: "Irak", flag: "🇮🇶" },
  "Oman": { fr: "Oman", flag: "🇴🇲" },
  "Vanuatu": { fr: "Vanuatu", flag: "🇻🇺" },
  "Cambodia": { fr: "Cambodge", flag: "🇰🇭" },
  "Thailand": { fr: "Thaïlande", flag: "🇹🇭" },
  "Laos": { fr: "Laos", flag: "🇱🇦" },
  "Myanmar": { fr: "Myanmar", flag: "🇲🇲" },
  "Vietnam": { fr: "Vietnam", flag: "🇻🇳" },
  "North Korea": { fr: "Corée du Nord", flag: "🇰🇵" },
  "South Korea": { fr: "Corée du Sud", flag: "🇰🇷" },
  "Mongolia": { fr: "Mongolie", flag: "🇲🇳" },
  "India": { fr: "Inde", flag: "🇮🇳" },
  "Bangladesh": { fr: "Bangladesh", flag: "🇧🇩" },
  "Bhutan": { fr: "Bhoutan", flag: "🇧🇹" },
  "Nepal": { fr: "Népal", flag: "🇳🇵" },
  "Pakistan": { fr: "Pakistan", flag: "🇵🇰" },
  "Afghanistan": { fr: "Afghanistan", flag: "🇦🇫" },
  "Tajikistan": { fr: "Tadjikistan", flag: "🇹🇯" },
  "Kyrgyzstan": { fr: "Kirghizistan", flag: "🇰🇬" },
  "Turkmenistan": { fr: "Turkménistan", flag: "🇹🇲" },
  "Iran": { fr: "Iran", flag: "🇮🇷" },
  "Syria": { fr: "Syrie", flag: "🇸🇾" },
  "Armenia": { fr: "Arménie", flag: "🇦🇲" },
  "Sweden": { fr: "Suède", flag: "🇸🇪" },
  "Belarus": { fr: "Biélorussie", flag: "🇧🇾" },
  "Ukraine": { fr: "Ukraine", flag: "🇺🇦" },
  "Poland": { fr: "Pologne", flag: "🇵🇱" },
  "Austria": { fr: "Autriche", flag: "🇦🇹" },
  "Hungary": { fr: "Hongrie", flag: "🇭🇺" },
  "Moldova": { fr: "Moldavie", flag: "🇲🇩" },
  "Romania": { fr: "Roumanie", flag: "🇷🇴" },
  "Lithuania": { fr: "Lituanie", flag: "🇱🇹" },
  "Latvia": { fr: "Lettonie", flag: "🇱🇻" },
  "Estonia": { fr: "Estonie", flag: "🇪🇪" },
  "Germany": { fr: "Allemagne", flag: "🇩🇪" },
  "Bulgaria": { fr: "Bulgarie", flag: "🇧🇬" },
  "Greece": { fr: "Grèce", flag: "🇬🇷" },
  "Turkey": { fr: "Turquie", flag: "🇹🇷" },
  "Albania": { fr: "Albanie", flag: "🇦🇱" },
  "Croatia": { fr: "Croatie", flag: "🇭🇷" },
  "Switzerland": { fr: "Suisse", flag: "🇨🇭" },
  "Luxembourg": { fr: "Luxembourg", flag: "🇱🇺" },
  "Belgium": { fr: "Belgique", flag: "🇧🇪" },
  "Netherlands": { fr: "Pays-Bas", flag: "🇳🇱" },
  "Portugal": { fr: "Portugal", flag: "🇵🇹" },
  "Spain": { fr: "Espagne", flag: "🇪🇸" },
  "Ireland": { fr: "Irlande", flag: "🇮🇪" },
  "New Caledonia": { fr: "Nouvelle-Calédonie", flag: "🇳🇨" },
  "Solomon Is.": { fr: "Îles Salomon", flag: "🇸🇧" },
  "New Zealand": { fr: "Nouvelle-Zélande", flag: "🇳🇿" },
  "Australia": { fr: "Australie", flag: "🇦🇺" },
  "Sri Lanka": { fr: "Sri Lanka", flag: "🇱🇰" },
  "China": { fr: "Chine", flag: "🇨🇳" },
  "Taiwan": { fr: "Taïwan", flag: "🇹🇼" },
  "Italy": { fr: "Italie", flag: "🇮🇹" },
  "Denmark": { fr: "Danemark", flag: "🇩🇰" },
  "United Kingdom": { fr: "Royaume-Uni", flag: "🇬🇧" },
  "Iceland": { fr: "Islande", flag: "🇮🇸" },
  "Azerbaijan": { fr: "Azerbaïdjan", flag: "🇦🇿" },
  "Georgia": { fr: "Géorgie", flag: "🇬🇪" },
  "Philippines": { fr: "Philippines", flag: "🇵🇭" },
  "Malaysia": { fr: "Malaisie", flag: "🇲🇾" },
  "Brunei": { fr: "Brunei", flag: "🇧🇳" },
  "Slovenia": { fr: "Slovénie", flag: "🇸🇮" },
  "Finland": { fr: "Finlande", flag: "🇫🇮" },
  "Slovakia": { fr: "Slovaquie", flag: "🇸🇰" },
  "Czechia": { fr: "République Tchèque", flag: "🇨🇿" },
  "Eritrea": { fr: "Érythrée", flag: "🇪🇷" },
  "Japan": { fr: "Japon", flag: "🇯🇵" },
  "Paraguay": { fr: "Paraguay", flag: "🇵🇾" },
  "Yemen": { fr: "Yémen", flag: "🇾🇪" },
  "Saudi Arabia": { fr: "Arabie Saoudite", flag: "🇸🇦" },
  "Antarctica": { fr: "Antarctique", flag: "🇦🇶" },
  "N. Cyprus": { fr: "Chypre du Nord", flag: "🏳️" },
  "Cyprus": { fr: "Chypre", flag: "🇨🇾" },
  "Morocco": { fr: "Maroc", flag: "🇲🇦" },
  "Egypt": { fr: "Égypte", flag: "🇪🇬" },
  "Libya": { fr: "Libye", flag: "🇱🇾" },
  "Ethiopia": { fr: "Éthiopie", flag: "🇪🇹" },
  "Djibouti": { fr: "Djibouti", flag: "🇩🇯" },
  "Somaliland": { fr: "Somaliland", flag: "🏳️" },
  "Uganda": { fr: "Ouganda", flag: "🇺🇬" },
  "Rwanda": { fr: "Rwanda", flag: "🇷🇼" },
  "Bosnia and Herz.": { fr: "Bosnie-Herzégovine", flag: "🇧🇦" },
  "Macedonia": { fr: "Macédoine du Nord", flag: "🇲🇰" },
  "Serbia": { fr: "Serbie", flag: "🇷🇸" },
  "Montenegro": { fr: "Monténégro", flag: "🇲🇪" },
  "Kosovo": { fr: "Kosovo", flag: "🇽🇰" },
  "Trinidad and Tobago": { fr: "Trinité-et-Tobago", flag: "🇹🇹" },
  "S. Sudan": { fr: "Soudan du Sud", flag: "🇸🇸" },
  "Vatican": { fr: "Vatican", flag: "🇻🇦" },
  "Micronesia": { fr: "Micronésie", flag: "🇫🇲" },
  "Marshall Is.": { fr: "Îles Marshall", flag: "🇲🇭" },
  "Tonga": { fr: "Tonga", flag: "🇹🇴" },
  "Singapore": { fr: "Singapour", flag: "🇸🇬" },
  "Seychelles": { fr: "Seychelles", flag: "🇸🇨" },
  "São Tomé and Principe": { fr: "São Tomé-et-Principe", flag: "🇸🇹" },
  "San Marino": { fr: "Saint-Marin", flag: "🇸🇲" },
  "Samoa": { fr: "Samoa", flag: "🇼🇸" },
  "St. Vin. and Gren.": { fr: "Saint-Vincent-et-les-Grenadines", flag: "🇻🇨" },
  "Saint Lucia": { fr: "Sainte-Lucie", flag: "🇱🇨" },
  "St. Kitts and Nevis": { fr: "Saint-Christophe-et-Niévès", flag: "🇰🇳" },
  "Palau": { fr: "Palaos", flag: "🇵🇼" },
  "Nauru": { fr: "Nauru", flag: "🇳🇷" },
  "Monaco": { fr: "Monaco", flag: "🇲🇨" },
  "Mauritius": { fr: "Maurice", flag: "🇲🇺" },
  "Malta": { fr: "Malte", flag: "🇲🇹" },
  "Maldives": { fr: "Maldives", flag: "🇲🇻" },
  "Liechtenstein": { fr: "Liechtenstein", flag: "🇱🇮" },
  "Kiribati": { fr: "Kiribati", flag: "🇰🇮" },
  "Grenada": { fr: "Grenade", flag: "🇬🇩" },
  "Dominica": { fr: "Dominique", flag: "🇩🇲" },
  "Comoros": { fr: "Comores", flag: "🇰🇲" },
  "Cabo Verde": { fr: "Cap-Vert", flag: "🇨🇻" },
  "Barbados": { fr: "Barbade", flag: "🇧🇧" },
  "Bahrain": { fr: "Bahreïn", flag: "🇧🇭" },
  "Antigua and Barb.": { fr: "Antigua-et-Barbuda", flag: "🇦🇬" },
  "Andorra": { fr: "Andorre", flag: "🇦🇩" },
};

export function getCountryInfo(name: string): CountryInfo {
  return COUNTRY_INFO[name] ?? { fr: name, flag: "🏳️" };
}
