// lib/countryTraits.ts
//
// Classification factuelle (pays enclavés / îles), indexée par le nom
// anglais world-atlas. Sources : Wikipedia "Landlocked country" et
// "List of island countries" (44 pays enclavés, ~47 nations insulaires
// présentes dans notre jeu de données sur les 48 recensées — Tuvalu n'est
// pas dans le dataset world-atlas utilisé).

export const LANDLOCKED_COUNTRIES = new Set<string>([
  // Afrique (16)
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Central African Rep.",
  "Chad",
  "Ethiopia",
  "Lesotho",
  "Malawi",
  "Mali",
  "Niger",
  "Rwanda",
  "S. Sudan",
  "Uganda",
  "Zambia",
  "Zimbabwe",
  "eSwatini",
  // Asie (12)
  "Afghanistan",
  "Armenia",
  "Azerbaijan",
  "Bhutan",
  "Kazakhstan",
  "Kyrgyzstan",
  "Laos",
  "Mongolia",
  "Nepal",
  "Tajikistan",
  "Turkmenistan",
  "Uzbekistan",
  // Europe (15, dont les 2 "doublement enclavés" Liechtenstein et Uzbekistan)
  "Andorra",
  "Austria",
  "Belarus",
  "Czechia",
  "Hungary",
  "Kosovo",
  "Liechtenstein",
  "Luxembourg",
  "Moldova",
  "Macedonia",
  "San Marino",
  "Serbia",
  "Slovakia",
  "Switzerland",
  "Vatican",
  // Amérique du Sud (2)
  "Bolivia",
  "Paraguay",
]);

export const ISLAND_COUNTRIES = new Set<string>([
  "Antigua and Barb.",
  "Bahamas",
  "Bahrain",
  "Barbados",
  "Brunei",
  "Cabo Verde",
  "Comoros",
  "Cuba",
  "Cyprus",
  "N. Cyprus",
  "Dominica",
  "Dominican Rep.",
  "Timor-Leste",
  "Fiji",
  "Grenada",
  "Haiti",
  "Iceland",
  "Indonesia",
  "Ireland",
  "Jamaica",
  "Japan",
  "Kiribati",
  "Madagascar",
  "Maldives",
  "Malta",
  "Marshall Is.",
  "Mauritius",
  "Micronesia",
  "Nauru",
  "New Zealand",
  "Palau",
  "Papua New Guinea",
  "Philippines",
  "St. Kitts and Nevis",
  "Saint Lucia",
  "St. Vin. and Gren.",
  "Samoa",
  "São Tomé and Principe",
  "Seychelles",
  "Singapore",
  "Solomon Is.",
  "Sri Lanka",
  "Taiwan",
  "Tonga",
  "Trinidad and Tobago",
  "United Kingdom",
  "Vanuatu",
]);
