// lib/usStates.ts
//
// Noms français des 50 États américains + District de Columbia, indexés par
// le nom anglais tel qu'il apparaît dans us-atlas (states-10m.json). Source :
// Wikipédia FR, "États des États-Unis". Les territoires (Guam, Porto Rico,
// Samoa américaines, Îles Mariannes du Nord, Îles Vierges américaines)
// présents dans le jeu de données us-atlas sont volontairement exclus.

export const US_STATE_NAMES_FR: Record<string, string> = {
  Alabama: "Alabama",
  Alaska: "Alaska",
  Arizona: "Arizona",
  Arkansas: "Arkansas",
  California: "Californie",
  Colorado: "Colorado",
  Connecticut: "Connecticut",
  Delaware: "Delaware",
  "District of Columbia": "District de Columbia",
  Florida: "Floride",
  Georgia: "Géorgie",
  Hawaii: "Hawaï",
  Idaho: "Idaho",
  Illinois: "Illinois",
  Indiana: "Indiana",
  Iowa: "Iowa",
  Kansas: "Kansas",
  Kentucky: "Kentucky",
  Louisiana: "Louisiane",
  Maine: "Maine",
  Maryland: "Maryland",
  Massachusetts: "Massachusetts",
  Michigan: "Michigan",
  Minnesota: "Minnesota",
  Mississippi: "Mississippi",
  Missouri: "Missouri",
  Montana: "Montana",
  Nebraska: "Nebraska",
  Nevada: "Nevada",
  "New Hampshire": "New Hampshire",
  "New Jersey": "New Jersey",
  "New Mexico": "Nouveau-Mexique",
  "New York": "New York",
  "North Carolina": "Caroline du Nord",
  "North Dakota": "Dakota du Nord",
  Ohio: "Ohio",
  Oklahoma: "Oklahoma",
  Oregon: "Oregon",
  Pennsylvania: "Pennsylvanie",
  "Rhode Island": "Rhode Island",
  "South Carolina": "Caroline du Sud",
  "South Dakota": "Dakota du Sud",
  Tennessee: "Tennessee",
  Texas: "Texas",
  Utah: "Utah",
  Vermont: "Vermont",
  Virginia: "Virginie",
  Washington: "Washington",
  "West Virginia": "Virginie-Occidentale",
  Wisconsin: "Wisconsin",
  Wyoming: "Wyoming",
};
